dubbo:
  application:
    name: stu_cls
  registry:
    address: zookeeper://192.168.184.222:2181
  protocol:
    port: -1
#      首次启动不检查
  consumer:
    check: false

#配置数据源
spring:
  datasource:
    url: jdbc:mysql:///db_cls?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver